services:
  - type: web
    name: telegram-yclients-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: PARTNER_TOKEN
        sync: false
      - key: USER_TOKEN
        sync: false
      - key: NTBA_FIX_350
        value: "1"
    healthCheckPath: /
    autoDeploy: true
    plan: free